packages:
  - './packages/*'
allowBuilds:
  nx: false
  unrs-resolver: false
lockfileIncludeTarballUrl: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@certifaction/*'
shamefullyHoist: true
