name: Publish

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  publish:
    name: Publish to GitHub Packages (npm)
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/') == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup environment
        uses: jdx/mise-action@v4

      - name: Get pnpm store directory
        id: pnpm-store-dir
        shell: bash
        run: |
          echo "dir=$(pnpm store path --silent)" >> ${GITHUB_OUTPUT}

      - name: pnpm cache
        uses: actions/cache@v5
        id: pnpm-cache
        with:
          path: ${{ steps.pnpm-store-dir.outputs.dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/mise.lock', '**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Extract package version
        run: |
          PACKAGE_VERSION=$(node -p "require('./lerna.json').version")
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Configure Git user
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Run prepare-ci
        run: |
          pnpm config set "//npm.pkg.github.com/:_authToken=${{ github.token }}"
          pnpm ci

      - name: Create Git tag
        run: |
          TAG="v${PACKAGE_VERSION}"
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"

      - name: Publish to GitHub Packages
        run: |
          # Lerna always uses npm tooling to publish packages, regardless of the npmClient set in the lerna.json file.
          # https://lerna.js.org/docs/troubleshooting#publishing-to-a-private-npm-registry-artifactory-npm-enterprise-etc
          npm config set "//npm.pkg.github.com/:_authToken=${{ github.token }}"
          if [ ${{ contains(env.PACKAGE_VERSION, '-') == true }} == true ]; then
              pnpm exec lerna publish from-package --dist-tag next --yes
          else
              pnpm exec lerna publish from-package --dist-tag latest --yes
          fi

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.PACKAGE_VERSION }}
          prerelease: ${{ contains(env.PACKAGE_VERSION, '-') }}
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
