name: Test

on:
    push:
        branches:
            - '**'

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: '21'
                  cache: 'npm'

            - name: Extract version
              run: |
                  PACKAGE_VERSION=$(node -p "require('./lerna.json').version")
                  echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

            - name: Test
              run: |
                  echo "Version: ${{env.PACKAGE_VERSION}}"
